web/router.ex
defmodule Minishop.Router do
  use Minishop.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Minishop.SessionPlug, repo: Minishop.Repo
    plug Minishop.Auth, repo: Minishop.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Minishop do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/category_search/:id", PageController, :category_search
    get "/display_product/:id", PageController, :display_product
    get "/your_cart", PageController, :your_cart
    # get "/checkout", PageController, :checkout
    get "/orders/new", OrderController, :new
    get "/checkout", OrderController, :new

    #    post "/", SessionController, :add
    get "/session/clear", SessionController, :clear
    #    get "/session/add_cart/:title", SessionController, :add_to_cart
    get "/cart/add_cart/:id", CartController, :add_to_cart
    post "/cart/add_item", CartController, :add_item

    get "/store", StoreController, :index
    get "/store/checkout", StoreController, :checkout
    get "/orders", OrderController, :index
    get "/orders/show/:id", OrderController, :show
    post "/orders/create", OrderController, :create

    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/addresses", AddressController, only: [:index, :show, :new,
      :create]

  end

  scope "/manage", Minishop do
    pipe_through [:browser, :authenticate_user]

    resources "/products", ProductController
#    resources "/orders", OrderController
    resources "/line_items", Line_ItemController

  end

  # Other scopes may use custom stacks.
  # scope "/api", Minishop do
  #   pipe_through :api
  # end
end

lib/minishop/user.ex
defmodule Minishop.User do
  use Minishop.Web, :model

  schema "users" do
    field :name, :string
    field :username, :string
    field :email, :string
    field :password, :string, virtual: true
    field :password_hash, :string
    has_many :orders, Minishop.Order
    has_many :addresses, Minishop.Address

    timestamps
  end

  def changeset(model, params \\ %{}) do
    model
    |> cast(params, ~w(name username email), [])
    |> validate_length(:username, min: 1, max: 20)
    |> validate_format(:email, ~r/@/)
    |> unique_constraint(:username, name: :username_index)
  end

  def registration_changeset(model, params) do
    model
    |> changeset(params)
    |> cast(params, ~w(password), [])
    |> validate_length(:password, min: 6, max: 100)
    |> put_pass_hash()
  end

  defp put_pass_hash(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
        put_change(changeset, :password_hash, Comeonin.Bcrypt.hashpwsalt(pass))
      _ ->
        changeset
    end
  end


end

web/controllers/user_controller.ex
defmodule Minishop.UserController do
  use Minishop.Web, :controller
  # alias Minishop.Order

  plug :authenticate_user when action in [:index, :show]

  def index(conn, _params) do
  #    case authenticate(conn) do
    #   %Plug.Conn{halted: true} = conn ->
      #   conn
    #conn ->
        users = Repo.all(Minishop.User)
        render conn, "index.html", users: users
        #end
  end

  #def show(conn, %{"id" => id}) do
  def show(conn, _params) do
    # user = Repo.get(Minishop.User, id)
    user = conn.assigns.current_user
    addresses = Repo.all(assoc(user, :addresses))
    orders = Repo.all(assoc(user, :orders))
    orders = Repo.preload(orders, :pay_type)

    render conn, "show.html", user: user, orders: orders, addresses: addresses
  end

  alias Minishop.User
  
  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.registration_changeset(%User{}, user_params)
    case Repo.insert(changeset) do
      {:ok, user} ->
        conn
        |> Minishop.Auth.login(user)
        |> put_flash(:info, "#{user.name} created!")
        |> redirect(to: page_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end


end

web/views/user_view.ex
defmodule Minishop.UserView do
  use Minishop.Web, :view
  alias Minishop.User

  def first_name(%User{name: name}) do
    name
    |> String.split(" ")
    |> Enum.at(0)
  end
  
  def render("user.json", %{user: user}) do
    %{id: user.id, username: user.username}
  end

end

web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table class="table">
  <%= for user <- @users do %>
    <tr>
      <td><%= render "user.html", user: user %></td>
      <td><%= link "View", to: user_path(@conn, :show, user.id) %></td>
    </tr>
  <% end %>
</table>

web/templates/user/new.html.eex
<div class="container">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
<h1>New User</h1>
<%= if @changeset.action do %>
  <div class="alert alert-danger">
    <p>Oops, someting went wrong! Please check the errors below.</p>
  </div>
<%= end %>

<%= form_for @changeset, user_path(@conn, :create), fn f -> %>
<div class="form-group">
  <%= text_input f, :name, placeholder: "Name", class: "form-control" %>
  <%= error_tag f, :name %>
</div>
<div class="form-group">
  <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
  <%= error_tag f, :username %>
</div>
<div class="form-group">
  <%= text_input f, :email, placeholder: "Email", class: "form-control" %>
  <%= error_tag f, :email %>
</div>
<div class="form-group">
  <%= text_input f, :password, placeholder: "Password", class: "form-control" %>
  <%= error_tag f, :password %>
</div>
<%= submit "Create User", class: "btn btn-primary" %>
<%= end %>

    </div>
    <div class="col-md-2">
    </div>
  </div>
</div>

web/templates/user/show.html.eex
<div class="container">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
      <h1>User Profile</h1>
      <%= render "user.html", user: @user %>
      <h2>Addresses</h2>
      <%= link "Add Address", to: address_path(@conn, :new) %>
      <%= render Minishop.AddressView, "index.html", [conn: @conn, user: @user,
      addresses: @addresses] %>
      <h3>Orders</h3>
      <%= render Minishop.SharedView, "order_list.html", [conn: @conn, orders:
        @orders] %>
    </div>
    <div class="col-md-2">
    </div>
  </div>
</div>

web/templates/user/user.html.eex
<strong>ID:</strong>
<%= @user.id %>
<br>
<strong>Name:</strong>
<%= @user.name %>
<br>
<strong>Username:</strong>
<%= @user.username %>
<br/>
<strong>Email:</strong>
<%= @user.email %>
<b><%= # first_name(@user) %></b> (<%= #@user.id %>)