web/router.ex
defmodule Minishop.Router do
  use Minishop.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Minishop.SessionPlug, repo: Minishop.Repo
    plug Minishop.Auth, repo: Minishop.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Minishop do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/category_search/:id", PageController, :category_search
    get "/display_product/:id", PageController, :display_product
    get "/your_cart", PageController, :your_cart
    # get "/checkout", PageController, :checkout
    get "/orders/new", OrderController, :new
    get "/checkout", OrderController, :new

    #    post "/", SessionController, :add
    get "/session/clear", SessionController, :clear
    #    get "/session/add_cart/:title", SessionController, :add_to_cart
    get "/cart/add_cart/:id", CartController, :add_to_cart
    post "/cart/add_item", CartController, :add_item

    get "/store", StoreController, :index
    get "/store/checkout", StoreController, :checkout
    get "/orders", OrderController, :index
    get "/orders/show/:id", OrderController, :show
    post "/orders/create", OrderController, :create

    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/addresses", AddressController, only: [:index, :show, :new,
      :create]

  end

  scope "/manage", Minishop do
    pipe_through [:browser, :authenticate_user]

    resources "/products", ProductController
#    resources "/orders", OrderController
    resources "/line_items", Line_ItemController

  end

  # Other scopes may use custom stacks.
  # scope "/api", Minishop do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Minishop.LayoutView do
  use Minishop.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Minishop!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand" href="#">Minishop</a>  
            </div>
            <ul class="nav navbar-nav">
              <li><%= link "Home", to: page_path(@conn, :index) %></li>
              <li><%= link "Your Cart", to: page_path(@conn, :your_cart) %></li>
              <li><%= link "Checkout", to: order_path(@conn, :new) %> </li>
              <%= if @current_user do %>
                <li><%= link @current_user.username, to: user_path(@conn, :show,
                @current_user)  %></li>
                <li>
                  <%= link "Log out", to: session_path(@conn, :delete,
                  @current_user), form: [class: "form-inline float-xs-left"],
                  method: "delete" %>
                </li>
              <% else %>
                <li><%= link "Register", to: user_path(@conn, :new) %></li>
                <li><%= link "Log in", to: session_path(@conn, :new) %></li>
              <% end %>
              <li><a href="http://localhost:4000/store">Store</a></li>
            </ul>
          </div>
        </nav>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

      <footer class="container">
        <ul class="nav navbar-nav">
          <li><a href="http://www...">About</a></li>
        </ul>
      </footer>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/store.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Minishop Store!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <!--        <span class="logo"></span> -->
      </header>

      <p>Helo</p>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <div id="columns">
        <div id="side">
          <a href="http://localhost:4000/">Home</a><br> 
          <a href="http://www....">FAQ</a><br> 
          <a href="http://www....">News</a><br> 
          <a href="http://www....">Contact</a><br> 
          <a href="http://localhost:4000/store">Store</a><br> 

          <small>
            <%= render Minishop.StoreView, "cart.html", %{dcart: @dcart, conn: @conn} %>
          </small>

        </div>
        <div id="main">
          <%= render @view_module, @view_template, assigns %>
        </div>
      </div>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>