web/router.ex
defmodule Minishop.Router do
  use Minishop.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Minishop.SessionPlug, repo: Minishop.Repo
    plug Minishop.Auth, repo: Minishop.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Minishop do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/category_search/:id", PageController, :category_search
    get "/display_product/:id", PageController, :display_product
    get "/your_cart", PageController, :your_cart
    # get "/checkout", PageController, :checkout
    get "/orders/new", OrderController, :new
    get "/checkout", OrderController, :new

    #    post "/", SessionController, :add
    get "/session/clear", SessionController, :clear
    #    get "/session/add_cart/:title", SessionController, :add_to_cart
    get "/cart/add_cart/:id", CartController, :add_to_cart
    post "/cart/add_item", CartController, :add_item

    get "/store", StoreController, :index
    get "/store/checkout", StoreController, :checkout
    get "/orders", OrderController, :index
    get "/orders/show/:id", OrderController, :show
    post "/orders/create", OrderController, :create

    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/addresses", AddressController, only: [:index, :show, :new,
      :create]

  end

  scope "/manage", Minishop do
    pipe_through [:browser, :authenticate_user]

    resources "/products", ProductController
#    resources "/orders", OrderController
    resources "/line_items", Line_ItemController

  end

  # Other scopes may use custom stacks.
  # scope "/api", Minishop do
  #   pipe_through :api
  # end
end

web/templates/page/checkout.html.eex
<div class="container">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
<h2>Checkout</h2>

<%= render Minishop.StoreView, "cart.html", %{dcart: @dcart, conn: @conn} %>
<%= form_for @changeset, order_path(@conn, :create), fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :address, class: "control-label" %>
    <%= textarea f, :address, class: "form-control" %>
    <%= error_tag f, :address %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :pay_type_id, class: "control-label" %>
    <%= select f, :pay_type_id, @pay_types, class: "form-control",
      prompt: "Choose a pay type" %>
    <%= error_tag f, :pay_type_id %>
  </div>

  <div class="form-group">
    <%= submit "Buy", class: "btn btn-primary" %>
  </div>
<% end %>


<%= link "Back", to: store_path(@conn, :index) %>
    </div>
    <div class="col-md-2">
    </div>
  </div>
</div>

web/templates/page/index.html.eex
<div class="well well-sm text-info">
  <h2><%= gettext "Welcome to %{name}", name: "Minishop" %></h2>
  <p class="lead">A small shopping cart for ecommerce explorations.</p>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-2">
      <h3>Categories</h3>
      <%= render Minishop.SharedView, "category_list.html", [conn: @conn,
        categories: @categories] %>
    </div>
    <div class="col-md-7">
      <h3>Catalog</h3>
      <%= render Minishop.SharedView, "product_list.html", %{conn: @conn,
                                    products: @products} %>
    </div>
    <div class="col-md-3">
<%= render Minishop.StoreView, "cart.html", %{dcart: @dcart, conn: @conn} %>
<!-- <%= # render "cart.html", assigns %> -->
    </div>
  </div
</div>

<h2>Add Product</h2>

    <%= form_for @conn, page_path(@conn, :index), [role: "form", as: :session], fn f -> %>

    <div class="form-group">
    <label for="product">Product:</label>
    <%= text_input f, :product, [class: "form-control", id: "product"] %>
    </div>
    <%= submit "Add Product", class: "btn btn-default" %>
    <% end %>

  <div class="container">
<a href="http://localhost:4000/store">Store</a><br> 
<%= link "Clear Session", to: session_path(@conn, :clear) %>
  </div>

web/templates/page/product_display.html.eex
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <h3>Categories</h3>
      <%= # render Minishop.SharedView, "category_list.html", [conn: @conn,
        #categories: @categories] %>
    </div>
    <div class="col-md-7">
<h2>Show product</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @product.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @product.description %>
  </li>

  <li>
    <strong>Image url:</strong>
    <%= @product.image_url %>
  </li>

  <li>
    <strong>Price:</strong>
    <%= @product.price %>
  </li>
</ul>

<%= form_for @conn, cart_path(@conn, :add_item), [as: :add_item], fn f ->  %>
<%=# use a different function name for this implementation  %>
<%= hidden_input(f, :id, [value: @product.id]) %>
<%= label(f, :qty, "Qty: ", class: "control-label") %>
<%= select(f, :qty, 1..10 ) %>
<%= submit "Add Item", [class: "btn btn-default btn-xs"]%>
<% end %>
        <%= #link "Add to Cart", to: cart_path(@conn, :add_to_cart,
        # @product.id), class: "btn btn-default btn-xs" %>
    </div>

    <div class="col-md-3">
<%=# render Minishop.StoreView, "cart.html", %{dcart: @dcart, conn: @conn} %>
<!-- <%= # render "cart.html", assigns %> -->
    </div>
  </div
</div>
<%= link "Edit", to: product_path(@conn, :edit, @product) %>
<%= link "Back", to: product_path(@conn, :index) %>

web/templates/page/search_results.html.eex
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <h3>Categories</h3>
      <%= # render Minishop.SharedView, "category_list.html", [conn: @conn,
        #categories: @categories] %>
    </div>
    <div class="col-md-7">
      <h3>Catalog</h3>
      <%= render Minishop.SharedView, "product_list.html", %{conn: @conn,
                                    products: @sresults} %>
    </div>
    <div class="col-md-3">
<%=# render Minishop.StoreView, "cart.html", %{dcart: @dcart, conn: @conn} %>
<!-- <%= # render "cart.html", assigns %> -->
    </div>
  </div
</div>

web/templates/page/your_cart.html.eex
<div class="container">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
      <div class="small">
        <h3>Your Cart</h3>
        <table class="table">
        <thead>
          <tr>
            <th> Qty </th>
            <th> SKU </th>
          <th> Title </th>
            <th> Price </th>
          </tr>
        </thead>
        <tbody>
        <%= for item <- @dcart do %>
          <tr>
            <td><b><%= item.qty %></b></td>
            <td><b><%= item.sku %></b></td>
            <td><b><%= item.title %></b></td>
            <td><b><%= decimal_to_currency(item.price) %></b></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <p><b>Total:  <%= decimal_to_currency(cart_total(@dcart)) %></b></p>

      <%= link "Checkout", to: order_path(@conn, :new), class: "btn btn-primary btn-md"  %>
    </div>
    </div>
    <div class="col-md-2">
    </div>
  </div>
</div>